### PR TITLE
Added option to define/restrict host instead of using wildcard

### PR DESCRIPTION
**Pull request by chen01**
Looking to be able to restrict host

Out of curiosity, what superclass are the methods in GoNotificationPlugin overriding? I had to remove the overrides to test it because it couldn't detect a superclass

### CODE REVIEW

**Comment by chen01** [comment]
@matt-richardson let me know what you think! 

Thanks!

**Comment by matt-richardson** [comment]
LGTM. Thanks!

**Comment by matt-richardson** [comment]
Of course, as soon as I hit merge, I remember that I was going to ask if you could add something to the readme.md about the new `host` option.

**Comment by matt-richardson** [comment]
Released - https://github.com/matt-richardson/gocd-websocket-notifier/releases/tag/0.4.1%2Bbuild.10.

To be honest, I don't know what the GoNotificationPlugin overrides where there for (it was a long time ago). I suspect they were in the plugin that I based this on (https://github.com/ashwanthkumar/gocd-slack-build-notifier). I probably should remove them.

**Comment by chen01** [comment]
As far as I can tell it works without the overrides, but if it hasn't caused an issue so far for you than it should be ok!

Thanks for reviewing this!

**Pull request merged**
