### PR TITLE
changed port, changed to https, override host verifier

### PR DESCRIPTION
**Pull request by chen01**
@matt-richardson 

The override is to resolve ssl cert issue with using localhost

### CODE REVIEW

**Comment by matt-richardson** [comment]
Doesn't GoCD launch HTTPS on 8154?

**Comment by chen01** [comment]
By default yes, but it appears that we've implemented ours to a different port, so I've just set it to that temporarily in the code to try it out. It resolved my "Connection Refused" issue

**Comment by matt-richardson** [comment]
Interestingly, it gets a different error on travis: https://travis-ci.org/matt-richardson/gocd-websocket-notifier/builds/160024956#L2705

**Comment by matt-richardson** [comment]
Ahh - that'd be because its passing in the HTTP port in from the test, but expecting it to be a HTTPS port inside here.

**Comment by chen01** [comment]
Actually let me redo this with the HTTP port and try it out

**Pull request closed without merging**
